wandb_version: 1

train:
  desc: null
  value: true
eval:
  desc: null
  value: false
render:
  desc: null
  value: false
save_video:
  desc: null
  value: false
sleep:
  desc: null
  value: -1
eval_episodes:
  desc: null
  value: 5
env:
  desc: null
  value: AntMaze
td3:
  desc: null
  value: false
num_episode:
  desc: null
  value: 25000
start_training_steps:
  desc: null
  value: 2500
writer_freq:
  desc: null
  value: 25
subgoal_dim:
  desc: null
  value: 15
load_episode:
  desc: null
  value: -1
model_save_freq:
  desc: null
  value: 2000
print_freq:
  desc: null
  value: 100
exp_name:
  desc: null
  value: null
model_path:
  desc: null
  value: model
log_path:
  desc: null
  value: log
policy_freq_low:
  desc: null
  value: 2
policy_freq_high:
  desc: null
  value: 2
buffer_size:
  desc: null
  value: 200000
batch_size:
  desc: null
  value: 100
buffer_freq:
  desc: null
  value: 10
train_freq:
  desc: null
  value: 10
reward_scaling:
  desc: null
  value: 0.1
time_horizon:
  desc: null
  value:
  - 1
  - 10
  - 15
  - 20
  - 25
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1719909133.987058
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      4: 3.9.17
      5: 0.15.8
      8:
      - 2
      - 3
      - 5
